"""empty message

Revision ID: 1a85917af39c
Revises: 51b26a433cf0
Create Date: 2014-08-06 23:43:12.697449

"""

# revision identifiers, used by Alembic.
revision = '1a85917af39c'
down_revision = '51b26a433cf0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
