"""empty message

Revision ID: 32032b2d758c
Revises: 598e90d66ee7
Create Date: 2014-08-06 22:39:10.391016

"""

# revision identifiers, used by Alembic.
revision = '32032b2d758c'
down_revision = '598e90d66ee7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
