"""empty message

Revision ID: 3945d673b187
Revises: 57a3cce66108
Create Date: 2014-08-06 21:11:51.863084

"""

# revision identifiers, used by Alembic.
revision = '3945d673b187'
down_revision = '57a3cce66108'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
