"""empty message

Revision ID: 51b26a433cf0
Revises: 621e9533a55
Create Date: 2014-08-06 23:39:02.683302

"""

# revision identifiers, used by Alembic.
revision = '51b26a433cf0'
down_revision = '621e9533a55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
