"""empty message

Revision ID: 576d6b2586f0
Revises: 3976203fb051
Create Date: 2014-08-18 13:52:09.753189

"""

# revision identifiers, used by Alembic.
revision = '576d6b2586f0'
down_revision = '3976203fb051'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
