"""empty message

Revision ID: 57a3cce66108
Revises: 560c2f254ee3
Create Date: 2014-08-06 15:55:54.143738

"""

# revision identifiers, used by Alembic.
revision = '57a3cce66108'
down_revision = '560c2f254ee3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=60), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    ### end Alembic commands ###
