"""empty message

Revision ID: 598e90d66ee7
Revises: 3945d673b187
Create Date: 2014-08-06 22:23:21.630608

"""

# revision identifiers, used by Alembic.
revision = '598e90d66ee7'
down_revision = '3945d673b187'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
