"""empty message

Revision ID: 5a08d54f0d17
Revises: 1a85917af39c
Create Date: 2014-08-06 23:45:00.401853

"""

# revision identifiers, used by Alembic.
revision = '5a08d54f0d17'
down_revision = '1a85917af39c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
