"""empty message

Revision ID: 621e9533a55
Revises: 32032b2d758c
Create Date: 2014-08-06 22:44:56.603583

"""

# revision identifiers, used by Alembic.
revision = '621e9533a55'
down_revision = '32032b2d758c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
